{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "20d1f97d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from scipy.optimize import curve_fit\n",
    "\n",
    "# ==========================================\n",
    "# 1. THE KINETIC MODEL LIBRARY\n",
    "# ==========================================\n",
    "\n",
    "def pso_model(t, M_eq, k):\n",
    "    \"\"\"Pseudo-Second-Order (PSO)\"\"\"\n",
    "    return (M_eq**2 * k * t) / (1 + M_eq * k * t)\n",
    "\n",
    "def avrami_model(t, M_eq, k, n):\n",
    "    \"\"\"Avrami\"\"\"\n",
    "    return M_eq * (1 - np.exp(-k * np.power(t, n)))\n",
    "\n",
    "def langmuir_model(t, M_eq, K):\n",
    "    \"\"\"Langmuir\"\"\"\n",
    "    return (M_eq * K * t) / (1 + K * t)\n",
    "\n",
    "def ldf_model(t, M_eq, k):\n",
    "    \"\"\"Linear Driving Force (LDF)\"\"\"\n",
    "    return M_eq * (1 - np.exp(-k * t))\n",
    "\n",
    "def fickian_model(t, k):\n",
    "    \"\"\"Fickian / Intra-particle Diffusion\"\"\"\n",
    "    return k * np.sqrt(t)\n",
    "\n",
    "def weibull_model(t, M_eq, k, n):\n",
    "    \"\"\"Weibull (Statistical spread of energies)\"\"\"\n",
    "    return M_eq * (1 - np.exp(-np.power(k * t, n)))\n",
    "\n",
    "# Hybrid Examples (You can add the rest following this pattern)\n",
    "def hybrid_pso_avrami(t, M_eq1, k1, M_eq2, k2, n):\n",
    "    return pso_model(t, M_eq1, k1) + avrami_model(t, M_eq2, k2, n)\n",
    "\n",
    "def hybrid_langmuir_avrami(t, M_eq1, K1, M_eq2, k2, n):\n",
    "    return langmuir_model(t, M_eq1, K1) + avrami_model(t, M_eq2, k2, n)\n",
    "\n",
    "\n",
    "# Dictionary mapping names to functions and parameter counts (k)\n",
    "MODELS = {\n",
    "    'PSO': {'func': pso_model, 'k': 2, 'bounds': (0, np.inf)},\n",
    "    'Avrami': {'func': avrami_model, 'k': 3, 'bounds': (0, np.inf)},\n",
    "    'Langmuir': {'func': langmuir_model, 'k': 2, 'bounds': (0, np.inf)},\n",
    "    'LDF': {'func': ldf_model, 'k': 2, 'bounds': (0, np.inf)},\n",
    "    'Fickian': {'func': fickian_model, 'k': 1, 'bounds': (0, np.inf)},\n",
    "    'Weibull': {'func': weibull_model, 'k': 3, 'bounds': (0, np.inf)},\n",
    "    'PSO-Avrami': {'func': hybrid_pso_avrami, 'k': 5, 'bounds': (0, np.inf)},\n",
    "    'Langmuir-Avrami': {'func': hybrid_langmuir_avrami, 'k': 5, 'bounds': (0, np.inf)}\n",
    "}\n",
    "\n",
    "# ==========================================\n",
    "# 2. THE FITTER & BAYESIAN SELECTION LOGIC\n",
    "# ==========================================\n",
    "\n",
    "def fit_stage_kinetics(time_array, mass_array):\n",
    "    \"\"\"\n",
    "    Fits all candidate models to a single stage's time/mass data.\n",
    "    Computes parameter errors via covariance, calculates BIC, and ranks models.\n",
    "    \"\"\"\n",
    "    n_points = len(time_array)\n",
    "    max_mass = np.max(mass_array)\n",
    "    results = []\n",
    "\n",
    "    for name, meta in MODELS.items():\n",
    "        # Dynamic initial guesses based on parameter count\n",
    "        if meta['k'] == 1:\n",
    "            p0 = [1.0]\n",
    "        elif meta['k'] == 2:\n",
    "            p0 = [max_mass, 1.0]\n",
    "        elif meta['k'] == 3:\n",
    "            p0 = [max_mass, 1.0, 1.0]\n",
    "        elif meta['k'] == 5:\n",
    "            p0 = [max_mass/2, 1.0, max_mass/2, 1.0, 1.0]\n",
    "            \n",
    "        try:\n",
    "            # curve_fit returns optimal parameters (popt) and the covariance matrix (pcov)\n",
    "            popt, pcov = curve_fit(\n",
    "                meta['func'], time_array, mass_array, \n",
    "                p0=p0, bounds=meta['bounds'], maxfev=10000\n",
    "            )\n",
    "            \n",
    "            # Extract standard errors from the diagonal of the covariance matrix\n",
    "            perr = np.sqrt(np.diag(pcov))\n",
    "            \n",
    "            # Calculate Residual Sum of Squares (RSS)\n",
    "            predictions = meta['func'](time_array, *popt)\n",
    "            rss = np.sum((mass_array - predictions)**2)\n",
    "            \n",
    "            # Calculate BIC\n",
    "            k = meta['k']\n",
    "            bic = n_points * np.log(rss / n_points) + k * np.log(n_points)\n",
    "            \n",
    "            # Formatting parameters and uncertainties into strings for clean output\n",
    "            param_str = \", \".join([f\"{val:.4f}±{err:.4f}\" for val, err in zip(popt, perr)])\n",
    "            \n",
    "            # Extract Avrami exponent (n) if applicable\n",
    "            avrami_n = None\n",
    "            if 'Avrami' in name:\n",
    "                avrami_n = popt[-1] # n is always the last parameter in our definitions\n",
    "                \n",
    "            results.append({\n",
    "                'Model': name,\n",
    "                'BIC': bic,\n",
    "                'RSS': rss,\n",
    "                'Parameters (±SE)': param_str,\n",
    "                'Avrami n': round(avrami_n, 3) if avrami_n else None,\n",
    "                'popt': popt # Keeping raw floats for potential plotting later\n",
    "            })\n",
    "            \n",
    "        except Exception as e:\n",
    "            # Model failed to converge\n",
    "            pass\n",
    "\n",
    "    if not results:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    # Create DataFrame and calculate Delta BIC\n",
    "    df_results = pd.DataFrame(results)\n",
    "    min_bic = df_results['BIC'].min()\n",
    "    df_results['Delta_BIC'] = df_results['BIC'] - min_bic\n",
    "    \n",
    "    # Sort by best fit (lowest BIC)\n",
    "    df_results = df_results.sort_values('Delta_BIC').reset_index(drop=True)\n",
    "    \n",
    "    # Flag statistical ties (Delta BIC < 6)\n",
    "    df_results['Statistical Tie'] = df_results['Delta_BIC'] < 6.0\n",
    "\n",
    "    return df_results\n",
    "\n",
    "# Example Usage (assuming you have extracted a stage's offset time and mass):\n",
    "# df_stage_fits = fit_stage_kinetics(time_10_20, mass_10_20)\n",
    "# print(df_stage_fits[['Model', 'Delta_BIC', 'Statistical Tie', 'Parameters (±SE)', 'Avrami n']])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "graphage13-sorption",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
